### ISSUE TITLE
Backspace isn't deleting in input widget

### ISSUE THREAD

**Issue by mrdxxm** [khonsulabs/gooey#113]
I've been playing with examples and meet a bug in  https://github.com/khonsulabs/gooey/blob/main/examples/gameui.rs

Input widget works fine before pushing anything to chat. After it deleting with backspace stops working.
I traced it to this "if":

https://github.com/khonsulabs/gooey/blob/8d3a4a42cfa1b68bba4bada58710b212abbb0e16/src/widgets/input.rs#L226C13-L228C14

<img width="356" alt="image" src="https://github.com/khonsulabs/gooey/assets/71557776/30c9ae56-5600-48ee-a8f2-c94ffb3897f5">

Somehow cursor offset isn't updated properly after pressing Enter and grows indefinitely. Even when line is empty it carries previous value.
<img width="347" alt="image" src="https://github.com/khonsulabs/gooey/assets/71557776/557af820-b79d-4283-b055-98d274fc7482">

Apple M1 Air
macOS 14.1.1 Build 23B81

**Comment by ecton** [comment]
Thank  you for reporting this! I applied a generalized fix to ensure the selection is always constrained, and I removed the erroneous bounds check that was preventing the delete from happening now that it's extraneous.
