### ISSUE TITLE
The repository is too large - more than 200MB after fresh clone

### ISSUE THREAD

**Issue by gosuwachu** [khonsulabs/gooey#115]
Is there some large file hiding somewhere in git history? Normally I wouldn't notice, but it took a long time for me to clone this repository while on holiday :)

**Comment by ecton** [comment]
This is almost certainly a result of several factors:

- This repository isn't just a few months old. There are two tags to completely separate trees of history that contain the previous iterations of this library that date back multiple years. Removing them would remove the previous contributors, while their code is not currently reachable from `main`, their ideas may still be in some ways.
- The `gh-pages` branch hosts auto-generated documentation and other resources. This currently contains some old resources from previous iterations, namely some demo mp4s that were automatically generated in CI. While the current iteration doesn't support  [offscreen rendering[#89), this will make a return.

I'll try to dig through the gh-pages branch and see if there's some cleanup that can be done. However, I'm reluctant to remove the former history from the previous iterations. I'll leave this open, and the more people are concerned about the repository size, the more likely I'll be more aggressive in my cleanup.

**Comment by gosuwachu** [comment]
Thanks! I am just flagging it up as potential obstacle to people trying `gooey` out and it getting a bit more traction. I have tried cloning the repo 2/3 times, but I suspect most people won't have as much perseverance :) I have played with the examples at it looks great.

**Comment by daxpedda** [comment]
In the meantime I think [shallow cloning](https://git-scm.com/docs/shallow) would help a lot.

@ecton I know we talked about this ages ago, but did you consider [`deploy-pages`](https://github.com/marketplace/actions/deploy-github-pages-site)? That way the site is not stored in a Git branch.

**Comment by ecton** [comment]
My issue with `deploy-pages` is that I can't keep archival releases. For example, Gooey used to have a user guide (and I'll almost certainly be adding one again), I would want to keep the tagged published versions as they would be linked to from the READMEs on those published crate versions.

With deploy-pages, the entire deployment is overwritten with whatever is in the artifact tar. I suppose I can create an elaborate workflow to pull the current pages data and modify it in place then resubmit it, but I'm more likely to migrate to [dossier/khonsu.dev](https://github.com/khonsulabs/dossier) -- I just haven't prioritized it.

**Comment by ecton** [comment]
After linking to Dossier and seeing the dead-simple steps in the readme, I went ahead and switched over from gh-pages to Dossier. A fresh clone is now 21MB, which may still be a bit on the large size, but it's literally an order of magnitude smaller.

I'm more likely to move the unrelated histories to archive repositories than I am to try to rewrite any blobs out of its history. For now, I'm going to call this solved! If anyone disagrees feel free to leave a comment and I'll reconsider addressing the former histories.

**Comment by gosuwachu** [comment]
@ecton thanks! I have tried cloning gooey and it is much better now.

**Comment by ecton** [comment]
Final update, the repo is now only 5.1mb on a fresh clone.
