### ISSUE TITLE
Make Button use an embedded widget

### ISSUE THREAD

**Issue by ecton** [khonsulabs/gooey#65]
After rich text labels (#64), users will want to be able to put rich text in their buttons. We should just have Button have a label widget.

It might be interesting to support any type of widget as the label widget. But, I'm not sure what the API for that would look like.

Another idea could be to allow Button to have any child widget as its content display, and the button just provides the clicky behavior and activation.

## Update

As per the comment and closing of #40, this task is now to replace the label string with a content widget.

**Comment by ModProg** [comment]
I think the latter is the best solution, also enables icons etc. on buttons

**Comment by ecton** [comment]
This was completed by @ModProg  in #72
