### ISSUE TITLE
Add multiwindow support

### ISSUE THREAD

**Issue by ecton** [khonsulabs/gooey#91]

**Comment by dagit** [comment]
Having used a few other rust gui libraries and bumped into this limitation, I would say add this support as early as you can. It is likely to impact your API in ways that are hard to foresee.

Also, yes please. Multiwindows is important to me.

**Comment by ecton** [comment]
I don't have a convenient way to link a gif/mp4 into a github issue, so I've shared [a demo gif](https://fosstodon.org/@ecton/111621079717548342) on my Mastodon. The example that's being shown is [examples/multi-window.rs](https://github.com/khonsulabs/gooey/blob/main/examples/multi-window.rs)

This wasn't too difficult for me to get working today because I had planned for it from the beginning.
