### ISSUE TITLE
Possibility for callback on Dynamic to not be called?

### ISSUE THREAD

**Issue by Plecra** [khonsulabs/gooey#97]
https://github.com/khonsulabs/gooey/blob/63fd92eea6d612708db0da3be4b05a3de4535f10/src/value.rs#L1024

I'm fairly sure it's possible for changes to get missed by this drop handler. We should set a flag that `change_happened` and the thread that `Acquire`d `currently_executing` can test it to know if it should continue.

**Comment by ecton** [comment]
This is almost certainly caused by a cycle of updates, which means if we did allow it, it would almost certainly be an infinite loop. This might get short-circuited with PartialEq, but it might not. That's why I elected to log and stop rather than try to recover.

**Comment by Plecra** [comment]
If there was a long-running handler, another thread could race and update the Dynamic, right?

At least, it seems like Dynamic is intended to be used between multiple threads

**Comment by ecton** [comment]
This warning is only if the current thread is already holding the Mutex. If another thread is holding, it will block the thread and wait until it can acquire the Mutex.

**Comment by Plecra** [comment]
Yeah, that confused me. It seems like the condition of the `if` only depends on the atomic, are you sure we can't get to this branch in another thread?

**Comment by ecton** [comment]
I am as confident as I can be with looking at code I wrote three months ago :laughing: I believe I use two mutexes to synchronize state, and the atomic is set inside of the "inner" mutex being held which prevents any other thread from entering that code at the same time.

**Comment by Plecra** [comment]
https://github.com/khonsulabs/gooey/blob/63fd92eea6d612708db0da3be4b05a3de4535f10/src/value.rs#L814

This code uses the Drop implementation, and is used from any caller. I don't see any mutexes guarding it? And the Drop implementation doesn't refer to any mutexes before the warning either.

**Comment by ecton** [comment]
Oops, I did have a brain fart on my memory there. This is simpler than I remembered, but that seems to be for the worse. You're right, there's a (probably unlikely) chance that between `drop(state)` and the atomic being set, a second thread could also invoke their map_mut through to this location.

It seems like the flag might need to be a Mutex<Option<ThreadId>> instead.
